### ISSUE TITLE
Have rugsaar.de for the RUGSaar user group :wink:

### ISSUE THREAD

**Issue by SweeD** [phoet/on_ruby#198]
Hello @phoet,

I would like to add our own domain `rugsaar.de` to `saar.onruby.de`

Can you tell me, where I need to target with the `CNAME record` ? 

`example.herokuapp.com` sure but what specific?  (you can DM me via @markusschwed as well) 

Thanks! <3

**Comment by phoet** [comment]
![cname](https://cloud.githubusercontent.com/assets/48745/12148337/265f4870-b49e-11e5-826a-9f8f819f4328.png)

the CNAME has to point to the `onruby.herokuapp.com	`

i already added the domain to heroku settings so it should work right away in case you change the CNAME:

```
± |master ✓| → heroku domains | grep rugsaar
rugsaar.de              onruby.herokuapp.com
www.rugsaar.de          onruby.herokuapp.com
```

be aware that root domains (rugsaar.de) usually cannot be CNAMEd and because of that i configure my dns provider (domainfactory) to redirect from the root domain to the `www.` subdomain which has the CNAME configured.

**Comment by SweeD** [comment]
Thanks! 

I'm going to set it up, now. :+1:

**Comment by phoet** [comment]
i also had to add the domain with 4882b535d128382231ed489cf23fe201da59883c

it is working now

**Comment by SweeD** [comment]
Ah, great! Thank you! :blush:

**Comment by phoet** [comment]
you are welcome. if there is anything you need help with, just ping me here. :tada:
