### ISSUE TITLE
Ability to create new groups at will from the onruby.de website

### ISSUE THREAD

**Issue by joermungandr** [phoet/on_ruby#206]
- administrative sign-off should be possile

**Comment by phoet** [comment]
i think that it should be quite easy to do some of these tasks directly from an admin interface. this would be the case for everything that is in the [whitelabel config](https://github.com/phoet/on_ruby/blob/master/config/whitelabel.yml).

other things will need to changed beforehand, ie pulling usergroup specific translations, images, stlyes and javascripts, so everything that is now [generated for a new usergroup](https://github.com/phoet/on_ruby/blob/master/lib/tasks/fork.rake#L10-L32).

some things won't be possible because they need changes in heroku or other resources like nameservers, github-auth.

since we are adding maybe one usergroup every 6 month, i don't see a high priority here.
