### ISSUE TITLE
Groups Search

### ISSUE THREAD

**Issue by joermungandr** [phoet/on_ruby#208]

**Comment by waterlink** [comment]
I believe, this is would be a nice feature. This is not a high priority on the other hand at the moment, since we have only 13 groups at the moment.

**Comment by phoet** [comment]
@joermungandr could you add more context to the issue, maybe in the form of a user-story? i would not know what exactly you'd mean by group search.

@waterlink i think so too. another thing is that the solution should be simple and not increase the complexity of the app by a lot.

**Comment by bitboxer** [comment]
What happend here is that @joermungandr talked about creating these tickets in the ruby berlin slack. Creating a sidechannel that no one that is following only this github repo will find and read. This lead to the confusion of @phoet here :sob: . If you go forward and use that slack channel as official discussion channel, it needs consensus by all and a hint in the readme here.

**Comment by bitboxer** [comment]
Ah and I don't think that creating tons of placeholder tickets is a good thing. This easily leads to a pile of tickets nobody understands anymore because the person creating those forgot to clearify them later on. A ticket _always_ needs to be in a state where everyone can understand what is going on.
