### ISSUE TITLE
Locationless events stopped working

### ISSUE THREAD

**Issue by PragTob** [phoet/on_ruby#566]
There was this cool feature when creating an event without a location it said "looking for a location" - the form just told me I have to provide a location :(

I can probably fix this myself but just right now don't have the time.

Thanks for all the work as always :green_heart:

**Comment by phoet** [comment]
@PragTob the workflow is a bit different right now:

if you do not create a new event you have this default on the homepage

![Screen Shot 2019-06-17 at 15 50 40](https://user-images.githubusercontent.com/48745/59609465-bcd71b80-9117-11e9-81d1-00f005663e21.png)

and it links to https://www.rug-b.de/locations/none 

if you think that it's worth creating a new event without having a location, than i can probably add this feature without much hassle.

for us in hamburg it's usually not helpful as we organize stuff in github and only create an event after we found a location, so that we can provide location, date and time at once.

**Comment by PragTob** [comment]
@phoet ah I think that's what I meant. Usually that's ok for me - unless I'm late. Then I like to already announce the talks on the website and that means I gotta have an event setup already :sweat_smile:

**Comment by phoet** [comment]
that's fair. i will see if can squeeze that in soonish
